product_analysis:
  description: >
    Analyze the given product website: {product_website}.
    Extra details provided by the customer: {product_details}.
    
    Focus on identifying unique features, benefits,
    and the overall narrative presented.
    
    Keep in mind, attention to detail is crucial for
    a comprehensive analysis. It's currently 2024.
  expected_output: >
    Your final report should clearly articulate the
    product's key selling points, its market appeal,
    and suggestions for enhancement or positioning.
    Emphasize the aspects that make the product stand out.

competitor_analysis:
  description: >
    Explore competitor of {product_website}.
    Extra details provided by the customer: {product_details}.
    
    Identify the top 3 competitors and analyze their
    strategies, market positioning, and customer perception.
  expected_output: >
    Your final report MUST include BOTH all context about {product_website}
    and a detailed comparison to whatever competitor they have competitors.

content_creation:
  description: "Create engaging content for Instagram posts based on product and competitor analysis"
  expected_output: "A set of compelling Instagram post content ideas that highlight product benefits and differentiate from competitors"

photography:
  description: "Take professional photographs that showcase the product's best features"
  expected_output: "High-quality product photographs optimized for Instagram, highlighting key features and benefits"

creative_review:
  description: "Review and approve all content and photographs to ensure alignment with brand strategy"
  expected_output: "Final approved content and photographs ready for Instagram campaign launch"

campaign_development:
  description: >
    You're creating a targeted marketing campaign for: {product_website}.
    Extra details provided by the customer: {product_details}.
    
    To start this campaign we will need a strategy and creative content ideas.
    It should be meticulously designed to captivate and engage
    the product's target audience.
    
    Based on your ideas your co-workers will create the content for the campaign.

  expected_output: >
    Your final answer MUST be ideas that will resonate with the audience and
    also include ALL context you have about the product and the customer.

instagram_ad_copy:
  description: >
    Craft an engaging Instagram post copy.
    The copy should be punchy, captivating, concise,
    and aligned with the product marketing strategy.
    
    Focus on creating a message that resonates with
    the target audience and highlights the product's
    unique selling points.
    
    Your ad copy must be attention-grabbing and should
    encourage viewers to take action, whether it's
    visiting the website, making a purchase, or learning
    more about the product.


  expected_output: >
    Your final answer MUST be 3 options for an ad copy for instagram that
    not only informs but also excites and persuades the audience.

take_photograph_task:
  description: >
    You are working on a new campaign for a super important customer,
    and you MUST take the most amazing photo ever for an instagram post
    regarding the product, you have the following copy: {ad_copy}
    
    This is the product you are working with: {product_website}.
    Extra details provided by the customer: {product_details}.
    
    Imagine what the photo you wanna take describe it in a paragraph.
    Here are some examples for you follow:
    
    - high tech airplaine in a beautiful blue sky in a beautiful sunset super cripsy beautiful 4k, professional wide shot
    - the last supper, with Jesus and his disciples, breaking bread, close shot, soft lighting, 4k, crisp
    - an bearded old man in the snows, using very warm clothing, with mountains full of snow behind him, soft lighting, 4k, crisp, close up to the camera
    
    Think creatively and focus on how the image can capture the audience's
    attention. Don't show the actual product on the photo.
  expected_output: >
    Your final answer must be 3 options of photographs, each with 1 paragraph
    describing the photograph exactly like the examples provided above.

review_photo_task:
  description: >
    Review the generated image and provide a detailed analysis.
    Consider the following aspects:
    1. Visual quality and composition
    2. Alignment with ad copy: {ad_copy}
    3. Brand message consistency
    4. Potential audience impact
    
    Calculate a final suitability score (0-100) based on these factors.
    
  expected_output: >
    Your final answer must include:
    1. A detailed review of the image
    2. A suitability score (0-100)
    3. Specific recommendations for improvements if needed